<a href="https://colab.research.google.com/github/Amit-Ramrakhyani/PyTorch-Notebooks/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals 

Reference = https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [2]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0][1]

tensor(8)

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[[2, 4, 7], 
                        [4, 7, 3], 
                        [0, 3, 8]], 
                       [[2, 4, 7], 
                        [4, 7, 3], 
                        [0, 3, 8]]]])
TENSOR

tensor([[[[2, 4, 7],
          [4, 7, 3],
          [0, 3, 8]],

         [[2, 4, 7],
          [4, 7, 3],
          [0, 3, 8]]]])

In [14]:
TENSOR.ndim

4

In [15]:
TENSOR.shape

torch.Size([1, 2, 3, 3])

In [16]:
TENSOR[0][1]

tensor([[2, 4, 7],
        [4, 7, 3],
        [0, 3, 8]])

 ### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Troch rabdom tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [17]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2455, 0.9566, 0.0500, 0.4785],
        [0.2762, 0.4558, 0.1765, 0.9115],
        [0.7290, 0.3669, 0.6032, 0.3049]])

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
# Use torch.range() and get deprecated message, use torch.arange()
torch.arange(2, 10, 2)

tensor([2, 4, 6, 8])

In [24]:
range = torch.arange(start=2, end=11, step=2)
range

tensor([ 2,  4,  6,  8, 10])

In [25]:
# Creating tensors like
five_zeros = torch.zeros_like(input=range)
five_zeros

tensor([0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16) # or you can use torch.half
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [31]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors on the right device - to get device from a tensor, can use `tensor.device`

In [32]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5914, 0.9286, 0.0669, 0.2441],
        [0.5922, 0.7270, 0.4073, 0.4755],
        [0.2562, 0.3488, 0.2704, 0.5917]])

In [33]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [34]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.5914, 0.9286, 0.0669, 0.2441],
        [0.5922, 0.7270, 0.4073, 0.4755],
        [0.2562, 0.3488, 0.2704, 0.5917]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor Operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication  

In [69]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [43]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [44]:
tensor

tensor([1, 2, 3])

In [45]:
# Subtract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [46]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [47]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [48]:
# Dividing tensor by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multipying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [94]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.4391, 0.3943, 0.1441],
        [0.4732, 0.3571, 0.2353],
        [0.3515, 0.2867, 0.1495]])

In [50]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [51]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [73]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [59]:
tensor

tensor([1, 2, 3])

In [53]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [93]:
# Matrix multiplication using for loop
%%time
value = 0
arr = [0, 1, 2]
for i in arr:
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.61 ms, sys: 0 ns, total: 1.61 ms
Wall time: 1.62 ms


In [92]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 139 µs, sys: 0 ns, total: 139 µs
Wall time: 163 µs


tensor(14)

### One of the most common errors in deep learning: Shape Errors

In [102]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [5, 6],
                        [9, 10]])

tensor_B = torch.tensor([[3, 4],
                         [7, 8],
                         [11, 12]])

torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)

RuntimeError: ignored

In [103]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [108]:
tensor_B, tensor_B.shape

(tensor([[ 3,  4],
         [ 7,  8],
         [11, 12]]), torch.Size([3, 2]))

In [106]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 3,  7, 11],
         [ 4,  8, 12]]), torch.Size([2, 3]))

In [111]:
# The matrix multiplication operation works  when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplication: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print ("Output: \n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplication: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 11,  23,  35],
        [ 39,  83, 127],
        [ 67, 143, 219]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [131]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [114]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [115]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [123]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [125]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [126]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [134]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs 
x.argmin(), x[x.argmin()]

(tensor(0), tensor(1))

In [135]:
# Find the position in tensor that has the maximum value with argmax() -> returns index position of target tensor where maximum value occurs 
x.argmax(), x[x.argmax()]

(tensor(9), tensor(91))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same menmory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [163]:
# Creating a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [154]:
# Add an extra dimension
x_reshaped = x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [160]:
# Change the view
z = x.view(3, 3)
z, z.shape

(tensor([[  1.,   2.,   3.],
         [  4.,   5.,   6.],
         [  7.,   8., 100.]]), torch.Size([3, 3]))

In [161]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[  5.,   2.,   3.],
         [  5.,   5.,   6.],
         [  5.,   8., 100.]]),
 tensor([  5.,   2.,   3.,   5.,   5.,   6.,   5.,   8., 100.]))

In [167]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [176]:
# Stack tensors in sequence vertically (row wise)
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.vstack([a, b]), torch.vstack([a, b]).shape

(tensor([[1, 2, 3],
         [4, 5, 6]]), torch.Size([2, 3]))

In [177]:
a = torch.tensor([[1], [2], [3]])
b = torch.tensor([[4], [5], [6]])
torch.vstack((a, b)), torch.vstack([a, b]).shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6]]), torch.Size([6, 1]))

In [179]:
# Stack tensors in sequence horizontally (column wise)
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
torch.hstack([a, b]), torch.hstack([a, b]).shape

(tensor([1, 2, 3, 4, 5, 6]), torch.Size([6]))

In [180]:
a = torch.tensor([[1], [2], [3]])
b = torch.tensor([[4], [5], [6]])
torch.hstack((a, b)), torch.hstack([a, b]).shape

(tensor([[1, 4],
         [2, 5],
         [3, 6]]), torch.Size([3, 2]))

In [216]:
# torch.squeeze() - Returns a tensor with all the dimensions of input of size 1 removed.
x = torch.tensor([[[1.], [2.], [3.], [4.], [5.]]])
x, x.shape

(tensor([[[1.],
          [2.],
          [3.],
          [4.],
          [5.]]]), torch.Size([1, 5, 1]))

In [212]:
y = torch.squeeze(x)  # or you can use x.squeeze([index of the 1th dimensions you want to squeeze])
y, y.shape

(tensor([1., 2., 3., 4., 5.]), torch.Size([5]))

In [213]:
y = torch.squeeze(x, 0)
y, y.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.]]), torch.Size([5, 1]))

In [215]:
y = torch.squeeze(x, 2)
y, y.shape

(tensor([[1., 2., 3., 4., 5.]]), torch.Size([1, 5]))

In [220]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)

y = torch.unsqueeze(x, dim=3) 
y, y.shape

(tensor([[[[1.]],
 
          [[2.]],
 
          [[3.]],
 
          [[4.]],
 
          [[5.]]]]), torch.Size([1, 5, 1, 1]))

In [223]:
y = torch.unsqueeze(x, dim=0) 
y, y.shape

(tensor([[[[1.],
           [2.],
           [3.],
           [4.],
           [5.]]]]), torch.Size([1, 1, 5, 1]))

In [237]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]
x.shape

torch.Size([224, 224, 3])

In [238]:
y = torch.permute(x, (2, 0, 1)) # [colour_channels, height, width]
y.shape

torch.Size([3, 224, 224])

In [239]:
print(x[0][0][0])
y[0, 0, 0] = 20
print(x[0, 0, 0])

tensor(0.9946)
tensor(20.)


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [241]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [244]:
# Let's index on the first bracket (dim=0)
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [246]:
# Let's index on the middle bracket (dim=1)
x[0, 0]

tensor([1, 2, 3])

In [248]:
# Let's index on the last bracket (dim=2)
x[0, 0, 0] # or you can use x[0][0][0]

tensor(1)

In [249]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [254]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1] 

tensor([[2, 5, 8]])

In [255]:
# Get all values of the 0th dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [256]:
# Get the values 6 and 9 from the tensor x
x[:, 1:, 2]

tensor([[6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data  in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)` 
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [263]:
# NumpPy array to tensor
import torch
import numpy as np

array = np.arange(1., 8.)
tensor = torch.from_numpy(array) # WARNING: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified othewise 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [264]:
array.dtype

dtype('float64')

In [265]:
tensor.dtype

torch.float64

In [266]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [267]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [268]:
numpy_tensor.dtype

dtype('float32')

In [269]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

Resources for reproducibilty:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

In [273]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8042, 0.5585, 0.1380, 0.1581],
        [0.9482, 0.1433, 0.5346, 0.9573],
        [0.4712, 0.0783, 0.2617, 0.8839]])
tensor([[0.3973, 0.8047, 0.7072, 0.5968],
        [0.3608, 0.8958, 0.6347, 0.8868],
        [0.1008, 0.1006, 0.0053, 0.9412]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [278]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, 
thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory :)

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a lil bit of setup and requires the investment of purchasing a GPU, there's lots of options... read this blog for what options to get https://timdettmers.com/category/deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a lil bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [1]:
!nvidia-smi

Fri Mar 10 14:44:40 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P0    25W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [4]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running comppute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU

In [15]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [6]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [9]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [16]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [17]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [19]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu.numpy()

array([1, 2, 3])

In [21]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')